// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainingManager.Logic.Storage;

#nullable disable

namespace TrainingManager.Logic.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20230416075554_InitBodyData")]
    partial class InitBodyData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryOfBodyExercise", b =>
                {
                    b.Property<string>("CategoryOfBodiesCode")
                        .HasColumnType("text");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.HasKey("CategoryOfBodiesCode", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("CategoryOfBodyExercise");
                });

            modelBuilder.Entity("ExerciseTrainingProgramDay", b =>
                {
                    b.Property<long>("ExercisesId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TrainingProgramDaysId")
                        .HasColumnType("uuid");

                    b.HasKey("ExercisesId", "TrainingProgramDaysId");

                    b.HasIndex("TrainingProgramDaysId");

                    b.ToTable("ExerciseTrainingProgramDay");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.Approach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfTraining")
                        .HasColumnType("integer");

                    b.Property<long>("TrainingId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingId");

                    b.ToTable("Approach");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.ApproachItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Hard")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfApproach")
                        .HasColumnType("integer");

                    b.Property<int>("Technicality")
                        .HasColumnType("integer");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<Guid>("approachId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("approachId");

                    b.ToTable("ApproachItem");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.CategoryOfBody", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<string>("Decsription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("AvatarId");

                    b.ToTable("CategoryOfBody");

                    b.HasData(
                        new
                        {
                            Code = "GrudinoKlyuchichnoSosceviddnayaMyshca",
                            Decsription = "Грудино-ключично-сосцевидная мышца представляет собой довольно крупный мышечный тяж на переднебоковой поверхности шеи. Располагается под подкожной мышцей шеи, отделяясь от нее шейной фасцией. Соединяет череп с грудиной и ключицей, разделяя шею на передний и задний треугольники.",
                            IsArchived = false,
                            Name = "Грудино-ключично-сосцевиддная мышца",
                            ShortName = "Грудино-ключично-сосцевиддная"
                        },
                        new
                        {
                            Code = "PoluosistayaMyshcaGolovy",
                            Decsription = "Полуостистая мышца головы располагается между поперечными отростками 5 верхних грудных позвонков и 3—4 нижних шейных с одной стороны и выйной площадкой затылочной кости – с другой. Посередине медиальной части мышцы располагается сухожильная перемычка.",
                            IsArchived = false,
                            Name = "Полуосистая мышца головы",
                            ShortName = "Полуосистая головная"
                        },
                        new
                        {
                            Code = "RemennayaMyshcaGolovy",
                            Decsription = "начинается от выйной связки, остистых отростков III- Vii шейного и 3 верхних грудных позвонков идет вверх и латерально и прикрепляется к боковому отделу верхней выйной линии и вдоль заднего края сосцевидного отростка. Прикрыта верхним отделом трапециевидной мышцы. При одностороннем сокращении мышца поворачивает голову в свою сторону, при двустороннем сокращении мышца разгибает шейную часть позвоночника и наклоняет голову назад.",
                            IsArchived = false,
                            Name = "Ременная мышца головы",
                            ShortName = "Ременная головная"
                        },
                        new
                        {
                            Code = "MyshcaPodnimayushchayaLopatku",
                            Decsription = "ШМышца, поднимающая лопатку, — располагается под трапециевидной мышцей. Начинаясь от задних бугорков поперечных отростков 4 верхних шейных позвонков, четырьмя отдельными сухожильными пучками, соединяется (иногда представлена несколькими отдельными мышцами) идет вниз и латерально, прикрепляясь к верхнему отделу медиального края лопатки и верхнему углу лопатки.",
                            IsArchived = false,
                            Name = "Мышца, поднимающая лопатку",
                            ShortName = "Поднимающая лопатку"
                        },
                        new
                        {
                            Code = "LestnichnayaMyshca",
                            Decsription = "Лестничные мышцы — мышцы шеи глубокого слоя боковой (латеральной) группы.Лестничные мышцы поднимают верхние рёбра, действуя как мышца вдоха. При фиксированных рёбрах, сокращаясь с обеих сторон, они сгибают шейную часть позвоночника спереди, а при одностороннем сокращении сгибают и поворачивают её в свою сторону.",
                            IsArchived = false,
                            Name = "Лестничная мышца",
                            ShortName = "Лестничная мышца"
                        },
                        new
                        {
                            Code = "LopatochnoPodyazychnayaMyshcaNizhneeBryushko",
                            Decsription = "парная мышца передней поверхности шеи из группы подподъязычных. Имеет длинную уплощенную форму, разделена сухожилием на два брюшка.",
                            IsArchived = false,
                            Name = "Лопаточно-подъязычная мышца, нижнее брюшко",
                            ShortName = "Лопаточно-подъязычная"
                        },
                        new
                        {
                            Code = "TrapecividnayaMyshca",
                            Decsription = "Трапециеви́дная мы́шца — плоская широкая мышца, занимающая поверхностное положение в задней области шеи и в верхнем отделе спины. Трапециевидная мышца имеет форму треугольника, основанием обращённого к позвоночному столбу, а вершиной — к акромиону лопатки. Трапециевидные мышцы обеих сторон спины вместе, как ни странно, имеют форму не трапеции (так как нет пары параллельных краёв мышцы и пары непараллельных краёв), а дельтоида — фигуры, образованной двумя симметричными треугольниками.",
                            IsArchived = false,
                            Name = "Трапецивидная мышца",
                            ShortName = "Трапецивидная мышца"
                        },
                        new
                        {
                            Code = "Akromion",
                            Decsription = "Латеральный конец лопаточной кости, сочленяющийся с акромиальной суставной поверхностью ключицы. Акромион образует вершину плеча, и представляет собой большую, немного треугольную или прямоугольную продолговатую форму, сплющенную сзади,которая выступает сначала поперечно, а затем изгибается вперед и вверх, чтобы выступать над суставной впадиной .[1]",
                            IsArchived = false,
                            Name = "Акромион",
                            ShortName = "Акромион"
                        },
                        new
                        {
                            Code = "Klyuchica",
                            Decsription = "в анатомии человека — небольшая трубчатая кость S-образной формы из пояса верхней конечности, соединяющая лопатку с грудиной и укрепляющая плечевой пояс.",
                            IsArchived = false,
                            Name = "Ключица",
                            ShortName = "Ключица"
                        },
                        new
                        {
                            Code = "DeltovidnayaMyshca",
                            Decsription = "Дельтовидная мышца — в анатомии человека — поверхностная мышца плеча, образующая его наружный контур. Принимает участие в сгибании и разгибании плеча, отведении руки в сторону. Название «дельтовидная» происходит по схожести треугольной формы мышцы с греческой буквой Δ (дельта).",
                            IsArchived = false,
                            Name = "Дельтовидная мышца",
                            ShortName = "Дельтовидная мышца"
                        },
                        new
                        {
                            Code = "DeltovidnayaMyshcaPered",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Дельтовидная мышца. Передняя часть",
                            ShortName = "Дельтовидная мышца"
                        },
                        new
                        {
                            Code = "DeltovidnayaMyshcaSrednya",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Дельтовидная мышца. Средняя часть.",
                            ShortName = "Дельтовидная мышца"
                        },
                        new
                        {
                            Code = "DeltovidnayaMyshcaZad",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Дельтовидная мышца. Задняя часть.",
                            ShortName = "Дельтовидная мышца"
                        },
                        new
                        {
                            Code = "BolshayaGrudnayaMyshcaGrudinoChychicnayaChast",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Болшая грудная мышца, ключицная часть",
                            ShortName = "Грудная мышца, ключицная часть"
                        },
                        new
                        {
                            Code = "BolshayaGrudnayaMyshcaGrudinoRebernayaChast",
                            Decsription = "Крупная поверхностная мышца веерообразной формы, расположенная на передней поверхности груди. Под ней находится треугольной формы малая грудная мышца.Грудино-реберная часть: начинается на передней поверхности грудины и хрящей верхних шести рёбер.",
                            IsArchived = false,
                            Name = "Болшая грудная мышца, грудино-реберная часть",
                            ShortName = "Грудная мышца, грудино-реберная часть"
                        },
                        new
                        {
                            Code = "BolshayaGrudnayaMyshcaAbdominalnayaChast",
                            Decsription = "Крупная поверхностная мышца веерообразной формы, расположенная на передней поверхности груди. Под ней находится треугольной формы малая грудная мышца.Абдоминальная часть: начинается на передней стенке прямой мышцы живота",
                            IsArchived = false,
                            Name = "Болшая грудная мышца, абдоминальная часть",
                            ShortName = "Грудная мышца, абдоминальная часть"
                        },
                        new
                        {
                            Code = "Grudina",
                            Decsription = "Продолговатая плоская кость в середине груди. Соединяется с рёбрами при помощи хрящей, формируя вместе с ними грудную клетку, вмещающую и защищающую от внешнего воздействия лёгкие, сердце и важнейшие кровеносные сосуды.",
                            IsArchived = false,
                            Name = "Грудина",
                            ShortName = "Грудина"
                        },
                        new
                        {
                            Code = "TricepsTrekhglavayaMyshcaPlechaDlinnayaGolovka",
                            Decsription = "Мышца-разгибатель задней группы плеча, занимает всю заднюю сторону плеча. От подсуставного бугорка лопатки;",
                            IsArchived = false,
                            Name = "Трицепс, трехглавая мышца плеча, длинная головка",
                            ShortName = "Трицепс, Трехглавая плеча, длинная гловка"
                        },
                        new
                        {
                            Code = "TricepsTrekhglavayaMyshcaPlechaMedialnayaGolovka",
                            Decsription = "Мышца-разгибатель задней группы плеча, занимает всю заднюю сторону плеча. От задней поверхности плечевой кости, межмышечных перегородок.",
                            IsArchived = false,
                            Name = "Трицепс, трехглавая мышца плеча, медиальная головка",
                            ShortName = "Трицепс, Трехглавая плеча, длинная гловка"
                        },
                        new
                        {
                            Code = "TricepsTrekhglavayaMyshcaPlechaLateralnayaGolovka",
                            Decsription = "Мышца-разгибатель задней группы плеча, занимает всю заднюю сторону плеча. От задней поверхности плеча",
                            IsArchived = false,
                            Name = "Трицепс, трехглавая мышца плеча, латеральная головка",
                            ShortName = "Трицепс, Трехглавая плеча, длинная гловка"
                        },
                        new
                        {
                            Code = "BicepsDvuglavayaMyshcaPlecha",
                            Decsription = "Большая мышца плеча, хорошо заметна под кожей.Сгибает плечо в плечевом суставе, предплечье в локтевом.",
                            IsArchived = false,
                            Name = "Бицепс (двуглавая мышца) плеча",
                            ShortName = "Бицепс плеча"
                        },
                        new
                        {
                            Code = "PlechevayaMyshca",
                            Decsription = "лежит глубже двуглавой мышцы плеча, начинается от передней поверхности плечевой кости и от обеих межмышечных перегородок, прикрепляется к бугристости локтевой кости.",
                            IsArchived = false,
                            Name = "Плечевая мышца",
                            ShortName = "Плечевая мышца"
                        },
                        new
                        {
                            Code = "PlecheluchevayaMyshca",
                            Decsription = "Мышца предплечья передней группы.Сгибает предплечье в локтевом суставе и устанавливает лучевую кость в положении, среднем между пронацией и супинацией.",
                            IsArchived = false,
                            Name = "Плечелучевая мышца",
                            ShortName = "Плечелучевая мышца"
                        },
                        new
                        {
                            Code = "BolshayaMyshcaSpiny",
                            Decsription = "Поверхностная мышца, занимающая всю нижнюю часть спины, верхние пучки в начальной части прикрыты трапециевидной мышцей.Приводит плечо к туловищу и тянет верхнюю конечность назад к срединной линии, вращая её внутрь — пронация. Если верхняя конечность закреплена, приближает к ней туловище и может расширять грудную клетку, служа вспомогательной дыхательной мышцей.",
                            IsArchived = false,
                            Name = "Большая мышца спины",
                            ShortName = "Большая мышца спины"
                        },
                        new
                        {
                            Code = "LoktevayaMyshca",
                            Decsription = "Небольшая пирамидальная мышца, являющаяся как бы продолжением медиальной головки трёхглавой мышцы плеча. Начинается от латерального надмыщелка плечевой кости и от лучевой коллатеральной связки. Прикрепляется к задней поверхности локтевого отростка, срастаясь с капсулой локтевого сустава.",
                            IsArchived = false,
                            Name = "Локтевая мышца",
                            ShortName = "Локтевая мышца"
                        },
                        new
                        {
                            Code = "BolshayaZubchatayaMyshca",
                            Decsription = "Расположена в переднем отделе грудной стенки. Верхняя её часть прикрыта большой грудной мышцей, нижняя расположена поверхностно, прикрыта грудной фасцией. Начинается 8—9 зубцами от наружной поверхности 8—9 рёбер, а также от сухожильной дуги между 1-м и 11-м рёбрами. Направляется назад и вверх, покрывает наружную поверхность рёбер, затем подходит под лопатку и прикрепляется вдоль её медиального края, а также к её нижнему углу. Наиболее выражены те части мышцы, место прикрепления которых располагается в области нижнего угла лопатки.",
                            IsArchived = false,
                            Name = "Большая зубчатая мышца",
                            ShortName = "Большая зубчатая мышца"
                        },
                        new
                        {
                            Code = "DlinnayaLadonnayaMyshca",
                            Decsription = "имеет короткое веретенообразное брюшко и очень длинное сухожилие. Лежит непосредственно под кожей, внутри от лучевого сгибателя запястья. Начинается от плечевой кости, межмышечной перегородки и фасции предплечья, подойдя к кисти, переходит в широкий ладонный апоневроз. Относится к рудиментам человеческого тела. Ранее служила для лазания по деревьям у обезьян. Общеизвестным фактом является то, что приблизительно у 15 % людей отсутствует сухожилие данной мышцы.",
                            IsArchived = false,
                            Name = "Длинная ладонная мышца",
                            ShortName = "Длинная ладонная мышца"
                        },
                        new
                        {
                            Code = "PoverhnostnyjSgibatelPalcevKisti",
                            Decsription = "Мышца передней группы предплечья.Спереди мышца прикрыта длинной ладонной мышцей и лучевым сгибателем запястья, которые оставляют на ней след в виде борозд.",
                            IsArchived = false,
                            Name = "Поверхностный сгибатель пальцев кисти",
                            ShortName = "Поверхностные сгибатель пальцев кисти"
                        },
                        new
                        {
                            Code = "RazgebatelPalcevKisti",
                            Decsription = "Мышца предплечья задней группы",
                            IsArchived = false,
                            Name = "Разгебатель пальцев кисти",
                            ShortName = "Разгебатель пальцев кисти"
                        },
                        new
                        {
                            Code = "SrednyayaYagodichnayaMyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Средняя ягодичная мышца",
                            ShortName = "Средняя ягодичная мышца"
                        },
                        new
                        {
                            Code = "SrednyayaYagodichnayaMyshcaPodYagodichnojFasciej",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Средняя ягодичная мышца, под ягодичной фасцией",
                            ShortName = "Средняя ягодичная мышца, под ягодичной фасцией"
                        },
                        new
                        {
                            Code = "BolshayaYagodichnayaMyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Большая ягодичная мышца",
                            ShortName = "Большая ягодичная мышца"
                        },
                        new
                        {
                            Code = "BolshojVertel",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Большой вертел",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "NapryagatelShirokojFascii",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Напрягатель широкой фасции",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "PodvzdoshnoBolshebercovyjTrakt",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Подвздошно-большеберцовый тракт",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "BicepsPlechaDlannayaGolovka",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Бицепс плеча, дланная головка",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "PromezhutochnayaShirokayaMyshcaBedra",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Промежуточная широкая мышца бедра",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "PodshovennayaMyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Подшовенная мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "BedroLateralnyjMyshchelok",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Бедро, латеральный мыщелок",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Menisk",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Мениск",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "ShejkaMalobercovojKosti",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Шейка малоберцовой кости",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "IkronozhnayaMyshcaLateralnayaGolovka",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Икроножная мышца, латеральная головка",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "KambapavidnayaMyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Камбапавидная мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "DlinnayaMalobercovayaMyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Длинная малоберцовая мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "DlinnyjRazgibatelPalcevStopy",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Длинный разгибатель пальцев стопы",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "KorotkayaMalobercovayaMyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Короткая малоберцовая мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "TretyaMalobercovayaMyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Третья малоберцовая мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "DlinnyjRazgibatelBoshogoPalcaStopy",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Длинный разгибатель большого пальца стопы",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "LateralnayaLodyshka",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Латеральная лодышка",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "KorotkijRazgibatelBolshogopalca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Короткий разгибатель большого пальца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "KorotkijRazgibatelPalcevStopy",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Короткий разгибатель пальцев стопы",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "MyshcaOtvodyashchayaMizinecStopy",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Мышца, отводящая мизинец стопы",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "MyshcaOtvodyashchayaBolshojPalecStopy",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Мышца, отводящая большой палец стопы",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "PervayaPlyusnevayaKost",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Первая плюсневая кость",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "MedialayaKlinovidnayaKost",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Медиальая клиновидная кость",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Ladevidnaya",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Ладьевидная кость",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "TarannayaKost",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Таранная кость",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "MedialnayaLodyzhka",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Медиальная лодыжка",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "PyatochnoeSuhozhilie",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Пяточное сухожилие",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "DlinnyjSgibatelBolshogoPalcaStopy",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Длинный сгибатель большого пальца стопы",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Dlinnyjsgibatelbolshogopalcevstopy",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Длинный сгибатель большого пальцев стопы",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "KambalovidnayaMyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Камбаловидная мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Perednyayabolshebercovayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Передняя большеберцовая мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Bolshebercovayakostmedialnayapoverhnost",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Большеберцовая кость, медиальная поверхность",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Ikronozhnayamyshcamedialnayagolovka",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Икроножная мышца, медиальная головка",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Bedromedialnyjmyshchelok",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Бедро, медиальный мыщелок",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Nadkolennik",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Надколенник",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Tonkayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Тонкая мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "PortnyazhnayaMyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Портняжная мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Dlinnayaprivodyashchayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Длинная приводящая мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Pryamayamyshcabedra",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Прямая мышца бедра",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Piramidalnayamyshcapodaponevrozom",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Пирамидальная мышца, под апоневрозом",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Myshcapodnimayushchayayaichko",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Мышца, поднимающая яичко",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Podvzdoshnoepoyasnichnayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Подвздошное поясничная мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Belayaliniyazhivota",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Белая линия живота",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Proksimalnayafalanga",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Проксимальная фаланга",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Detalnayafalanga",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Детальная фаланга",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Vtorayapyastnayakost",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Вторая пястная кость",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Tenar",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Тенар",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Poverhostnyjsgibatelpalcevruki",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Поверхостный сгибатель пальцев руки",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Luchevojsgibatelzapyastya",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Лучевой сгибатель запястья",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Korotkijluchevojrvzgibatelzapyastya",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Короткий лучевой рвзгибатель запястья",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Dlinnyjluchevojrazgibatelzapyastya",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Длинный лучевой разгибатель запястья",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Kruglyjpronator",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Круглый пронатор",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "PodvzdoshnayaKost",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Подвздошная кость",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "PryamayaMyshcaZhivota",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Прямая мышца живота",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Naruzhnayakosayamyshcazhivota",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Наружная косая мышца живота",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Bolshayagrudnayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Большая грудная мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Sedmojshejnyepozvonokostistyjostrovok",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Седьмой шейные позвонок, остистый островок",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Trapecevidnayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Трапецевидная мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Grebenlopatki",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Гребень лопатки",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Podostnayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Подостная мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Malayakruglayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Малая круглая мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Bolshayakruglayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Большая круглая мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Bolshayarombovidnayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Большая ромбовидная мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Grudnojpozvonokostistyjostrovok",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Грудной позвонок, остистый островок",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Torakolyumbalnayafasciya",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Тораколюмбальная фасция",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Poyasnichnyjtreugolnik",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Поясничный треугольник",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Podvzdoshnayaost",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Подвздошная ость",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Krestecdorsalnayapoverhnost",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Крестец, дорсальная поверхность",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Polusuhozhilnayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Полусухожильная мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Klyuvovidnoplechevayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Клювовидно-плечевая мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "TricepsPlecha",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Трицепс плеча",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Loktevojotrostok",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Локтевой отросток",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Loktevojsgibatelzapyastya",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Локтевой сгибатель запястья",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Loktevojrazgibatelzapyastya",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Локтевой разгибатель запястья",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Dlinnayamyshcaotvodyashchayabolshojpaleckisti",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Длинная мышца, отводящая большой палец кисти",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Dlinnyjsgibatelbolshogopalcakisti",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Длинный сгибатель большого пальца кисти",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Gorohovdnayamyshcaotvodyashchayabolshojpaleckisti",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Гороховдная мышца, отводящая большой палец кисти",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Korotkayamyshcaotvodyashchayabolshojpaleckisti",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Короткая мышца, отводящая большой палец кисти",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Ladonnyjaponevroz",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Ладонный апоневроз",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Distalnayafalanga",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Дистальная фаланга",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Razgibatelpalcevkistisuhozhilie",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Разгибатель пальцев кисти, сухожилие",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Bolshayaprivodyashchayamyshchca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Большая приводящая мыщца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Lateralnayashirokayamyshcabedra",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Латеральная широкая мышца бедра",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Bicepsbedra",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Бицепс бедра",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Bedrennayakostpodkolennayapoverhnost",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Бедренная кость, подколенная поверхность",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Podoshvennayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Подошвенная мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Ikronozhnayamyshcasuhozhilie",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Икроножная мышца, сухожилие",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Bugristostpyatochnojkosti",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Бугристость пяточной кости",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Grudinopoyazychnayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Грудино-поъязычная мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Perednyayazubchatayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Передняя зубчатая мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Lateralnyjnadmyshchelok",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Латеральный надмыщелок",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Pupochnoekolco",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Пупочное кольцо",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Kosayavnutrennyayamyshcazhivota",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Косая внутренняя мышца живота",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Kosayavnutrennyayamyshcazhivotapodaponevrozom",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Косая внутренняя мышца живота (под апоневрозом)",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Podvzdoshnopoyasnichnayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Подвздошно-поясничная мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "GrebenchatayaMyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Гребенчатая мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Medialnayashirokayamyshcabedra",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Медиальная широкая мышца бедра",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Svyazkanadkolennika",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Связка надколенника",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "BugristostbolshebercovojKosti",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Бугристость большеберцовой кости",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Ikronozhnayamyshca",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Икроножная мышца",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Dlinnyjsgibatelpalcevstopy",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Длинный сгибатель пальцев стопы",
                            ShortName = ""
                        },
                        new
                        {
                            Code = "Lopatochnopodyazychnayamyshcanizhneeboyushk",
                            Decsription = "",
                            IsArchived = false,
                            Name = "Лопаточно-подъязычная мышца, нижнее боюшко",
                            ShortName = ""
                        });
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HardSkill")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBased")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.Goal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Goal");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SizeItemId")
                        .HasColumnType("uuid");

                    b.Property<long?>("TrainingProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("SizeItemId");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.Size", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.SizeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeUnitsOfMeasurement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BodyCode");

                    b.HasIndex("CodeUnitsOfMeasurement");

                    b.HasIndex("SizeId");

                    b.ToTable("SizeItem");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.SubGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeUnitsOfMeasurement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("GoalId")
                        .HasColumnType("bigint");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BodyCode");

                    b.HasIndex("CodeUnitsOfMeasurement");

                    b.HasIndex("GoalId");

                    b.ToTable("SubGoal");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.Training", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TrainingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("TrainingProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("Training");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.TrainingProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("TrainingProgram");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.TrainingProgramDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayRelax")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfTrainingProgram")
                        .HasColumnType("integer");

                    b.Property<long>("TrainingProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("TrainingProgramDay");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.UnitsOfMeasurement", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("UnitsOfMeasurements");
                });

            modelBuilder.Entity("CategoryOfBodyExercise", b =>
                {
                    b.HasOne("TrainingManager.Logic.Storage.Domain.CategoryOfBody", null)
                        .WithMany()
                        .HasForeignKey("CategoryOfBodiesCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingManager.Logic.Storage.Domain.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExerciseTrainingProgramDay", b =>
                {
                    b.HasOne("TrainingManager.Logic.Storage.Domain.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingManager.Logic.Storage.Domain.TrainingProgramDay", null)
                        .WithMany()
                        .HasForeignKey("TrainingProgramDaysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.Approach", b =>
                {
                    b.HasOne("TrainingManager.Logic.Storage.Domain.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId");

                    b.HasOne("TrainingManager.Logic.Storage.Domain.Training", "Training")
                        .WithMany("Approachs")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.ApproachItem", b =>
                {
                    b.HasOne("TrainingManager.Logic.Storage.Domain.Approach", "approach")
                        .WithMany("ApproachsItems")
                        .HasForeignKey("approachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("approach");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.CategoryOfBody", b =>
                {
                    b.HasOne("TrainingManager.Logic.Storage.Domain.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.Exercise", b =>
                {
                    b.HasOne("TrainingManager.Logic.Storage.Domain.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.Image", b =>
                {
                    b.HasOne("TrainingManager.Logic.Storage.Domain.Exercise", null)
                        .WithMany("Images")
                        .HasForeignKey("ExerciseId");

                    b.HasOne("TrainingManager.Logic.Storage.Domain.SizeItem", null)
                        .WithMany("Images")
                        .HasForeignKey("SizeItemId");

                    b.HasOne("TrainingManager.Logic.Storage.Domain.TrainingProgram", null)
                        .WithMany("Images")
                        .HasForeignKey("TrainingProgramId");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.SizeItem", b =>
                {
                    b.HasOne("TrainingManager.Logic.Storage.Domain.CategoryOfBody", "Body")
                        .WithMany()
                        .HasForeignKey("BodyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingManager.Logic.Storage.Domain.UnitsOfMeasurement", "UnitsOfMeasurement")
                        .WithMany()
                        .HasForeignKey("CodeUnitsOfMeasurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingManager.Logic.Storage.Domain.Size", "Size")
                        .WithMany("SizeItems")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Body");

                    b.Navigation("Size");

                    b.Navigation("UnitsOfMeasurement");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.SubGoal", b =>
                {
                    b.HasOne("TrainingManager.Logic.Storage.Domain.CategoryOfBody", "Body")
                        .WithMany()
                        .HasForeignKey("BodyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingManager.Logic.Storage.Domain.UnitsOfMeasurement", "UnitsOfMeasurement")
                        .WithMany()
                        .HasForeignKey("CodeUnitsOfMeasurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingManager.Logic.Storage.Domain.Goal", "Goal")
                        .WithMany("SubGoals")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Body");

                    b.Navigation("Goal");

                    b.Navigation("UnitsOfMeasurement");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.Training", b =>
                {
                    b.HasOne("TrainingManager.Logic.Storage.Domain.TrainingProgram", "TrainingProgram")
                        .WithMany()
                        .HasForeignKey("TrainingProgramId");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.TrainingProgram", b =>
                {
                    b.HasOne("TrainingManager.Logic.Storage.Domain.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.TrainingProgramDay", b =>
                {
                    b.HasOne("TrainingManager.Logic.Storage.Domain.TrainingProgram", "TrainingProgram")
                        .WithMany("Days")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.Approach", b =>
                {
                    b.Navigation("ApproachsItems");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.Exercise", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.Goal", b =>
                {
                    b.Navigation("SubGoals");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.Size", b =>
                {
                    b.Navigation("SizeItems");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.SizeItem", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.Training", b =>
                {
                    b.Navigation("Approachs");
                });

            modelBuilder.Entity("TrainingManager.Logic.Storage.Domain.TrainingProgram", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
